#ifndef ALIGENEVTGEN_DEV_H
#define ALIGENEVTGEN_DEV_H

/* Copyright(c) 2007-2009, ALICE Experiment at CERN, All rights reserved. *
 * See cxx source for full Copyright notice                               */
///////////////////////////////////////////////////////////////////////////
//                                                                       //
//  AliGenEvtGen_dev class to performs decays of particles generated by a    //
//  previous generator. It inherits from AliGenerator.                   //
//                                                                       //  
//  Origin: Giuseppe.Bruno@ba.infn.it  &  Fiorella.Fionda@ba.infn.it     //
///////////////////////////////////////////////////////////////////////////

#include "AliGenerator.h"
#include "AliDecayerEvtGen.h"

class TParticle;

class AliGenEvtGen_dev : public AliGenerator {

public:

  typedef enum {kAllPart, kBeautyPart, kCharmPart} DecayOff_t;

  AliGenEvtGen_dev();
  ~AliGenEvtGen_dev();

  virtual void Init();
  virtual void Generate(); 
  Bool_t SetUserDecayTable(const char* path);
  void SetSeed(UInt_t /*seed*/) {;}

  AliDecayer*  GetDecayer()                             { return fDecayer     ; }
  void         SetForceDecay(Decay_t decay = kAll)      { fForceDecay  = decay; } //set a decay mode
  void         SetParticleSwitchedOff(DecayOff_t decay) { fSwitchOff   = decay; } //set particles to be decayed by EvtGen

protected:
  Int_t GetFlavour(Int_t pdgCode); 


private:
  Decay_t            fForceDecay;          ///<  decay case
  DecayOff_t         fSwitchOff;           ///<  particle decay
  Bool_t             fUserDecay;           ///<  TRUE if a user decay table is set
  TString            fUserDecayTablePath;  ///<  pointer to path of user decay table
  AliStack          *fStack;		           //!<! pointer to AliStack
  AliDecayerEvtGen  *fDecayer;             //!<! pointer to AliDecayerEvtGen

  AliGenEvtGen_dev(const AliGenEvtGen_dev &EvtGen);
  AliGenEvtGen_dev & operator=(const AliGenEvtGen_dev & rhs);

  ClassDef(AliGenEvtGen_dev, 1) //AliGenerator interface to EvtGen
};

////////////////////////////////////////////////////////////////////////////////////////////////

#endif
